version: '3.6'
services:
  node:
    container_name: node_coder_compose
    restart: always
    image: coder39740:1.0
    ports:
      - 8081:8080
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    networks:
      - codernet

  db:
    container_name: db_coder_compose
    restart: always
    image: bitnami/mongodb:4.2
    ports:
      - "27018:27017"
    environment:
      - MONGODB_ROOT_PASSWORD=123456
      - MONGODB_USERNAME=coder
      - MONGODB_PASSWORD=coder
      - MONGODB_DATABASE=coder

networks:
  codernet:
    driver: "bridge"
